___

<img src='../BootcampBack.png' /></a>
___

# NumPy Exercises 

Here are some exercises to test your NumPy skills. The tasks difficulty will become progressivly harder.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 8 ones

In [2]:
arr=np.ones(8)
arr

array([1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 15 zeros 

In [3]:
arr2=np.zeros(15)
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 6 nines

In [4]:
arr3=np.array([9,9,9,9,9,9])
arr3

arr4=np.repeat(9,6)
arr4

array([9, 9, 9, 9, 9, 9])

#### Create an array of the integers from 30 to 60

In [5]:
np.arange(30,60)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

#### Create an array of all the odd integers from 21 to 45

In [6]:
np.arange(21,46,2)

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45])

#### Create a 4x3 matrix with values ranging from 1 to 12

In [17]:
c=np.arange(1,13)
c
c.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### Create a 5x5 identity matrix

In [8]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [9]:
np.random.rand(1)

array([0.78009741])

#### Use NumPy to generate an array of 10 random numbers sampled from a standard normal distribution

In [3]:
np.random.randn(10)

array([-0.82328349,  1.58766321,  0.47523449, -1.15782532,  0.4400622 ,
        0.73596079,  0.1209468 ,  0.59441023,  1.62987628, -1.77816643])

#### Create the following matrix:

In [19]:
d=np.arange(0.3,1.5,0.1)
d.reshape(6,2)

array([[0.3, 0.4],
       [0.5, 0.6],
       [0.7, 0.8],
       [0.9, 1. ],
       [1.1, 1.2],
       [1.3, 1.4]])

#### Create an array of 9 linearly spaced points between 0 and 1:

In [20]:
np.linspace(0,1,9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [100]:
f=np.arange(25,45,1)
f1=f.reshape(5,4)
f1


array([[25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44]])

In [51]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [97]:
g=np.arange(34,45,1)
h=np.delete(g,[3,7],None)
h
#e=g[0:3]
#e
#f=g[4:7]
#f
#t=g[8:11]
#t
#matrix=([e,f,t])
#matrix

array([34, 35, 36, 38, 39, 40, 42, 43, 44])

In [53]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [60]:
a=39
a

39

In [57]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [63]:
my_matrix= [[26],[30],[34]]
my_matrix
np.array(my_matrix)

array([[26],
       [30],
       [34]])

In [59]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [65]:
p=[41,42,43,44]
np.array(p)

array([41, 42, 43, 44])

In [61]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [78]:
r=np.arange(37,45,1)
r
q=r.reshape(2,4)
q

array([[37, 38, 39, 40],
       [41, 42, 43, 44]])

### Now do the following

#### Get the sum of all the values in mat

In [103]:
f1.sum()

690

#### Get the mean of the values in mat

In [102]:
f1.mean()

34.5

#### Get the sum of all the rows in mat

In [101]:
s=f1.sum(0)
s


array([165, 170, 175, 180])